add selinux labels for QAT
intel/intel-device-plugins-for-kubernetes pull request #1163
Opened 2022-09-16 15:51 UTC by mregmi

Add the SELinux labels for QAT plugins.

Signed-off-by: Manish Regmi <manish.regmi@intel.com>

2022-09-19 07:19 UTC, mythi approved these changes

2022-09-19 07:21 UTC, mythi requested changes
I missed on part about "kernel-plugin.yaml". We don't need to change that.

2022-09-19 07:21 UTC, mythi commented on deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml
> +            type: "container_device_plugin_t"
drop this part.

2022-09-19 22:32 UTC, mregmi commented on deployments/qat_plugin/base/intel-qat-kernel-plugin.yaml
> +            type: "container_device_plugin_t"
removed.

2022-09-20 04:14 UTC, mythi approved these changes

2022-09-20 04:14 UTC, merged