Use more generic name for NFD features host directory volume
intel/intel-device-plugins-for-kubernetes pull request #1327
Opened 2023-02-08 16:32 UTC by eero-t

NFD hooks are deprecated and going away:
https://github.com/kubernetes-sigs/node-feature-discovery/issues/856

This makes the mount names more future-proof, and shows where later changes need to be done (to change operator mount directory, and switch hook-using deployments e.g. to feature files).

I decided to split this from PR https://github.com/intel/intel-device-plugins-for-kubernetes/pull/1118, so that same change can be done for all plugins (GPU + SGX), to avoid complicating later switch away from hooks.  Added SGX part is not tested, but that change is identical to GPU one.

2023-02-09 07:08 UTC, tkatila approved these changes

2023-02-09 18:08 UTC, eero-t commented
> e2e-gpu
> This request was automatically failed because there were no enabled runners online to process the request for more than 1 days

@mythi Any idea when runners will be available?

2023-02-09 18:53 UTC, tkatila commented
> Any idea when runners will be available?

WIP, the host is down for some reason.

2023-02-10 09:53 UTC, eero-t commented
@tkatila thanks!   Let me know when GPU runner is up again, and I'll rebase this to HEAD, to force re-testing.

2023-02-10 09:57 UTC, eero-t commented
/lgtm  Doc looks good now (and I checked that all links are fine).

2023-02-10 12:02 UTC, hj-johannes-lee requested changes
LGTM! / sorry for misclicking "change request"

2023-02-10 12:02 UTC, hj-johannes-lee approved these changes

2023-02-10 14:46 UTC, mythi approved these changes

2023-02-13 07:37 UTC, tkatila commented
@eero-t e2e gpu became online and tested ok.

2023-02-13 09:45 UTC, merged