Introduce bug and feature request templates
intel/intel-device-plugins-for-kubernetes pull request #1647
Opened 2024-01-09 09:41 UTC by tkatila

2024-01-09 11:00 UTC, eero-t requested changes
"A clear and concise" is repeated a lot though, maybe just one of the adjectives would be enough?

2024-01-09 11:00 UTC, eero-t commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Hardware info [e.g. SPR with QAT]:
Consistent use of version & double-colon, request also device plugins version:
```suggestion
 - OS version: [e.g. Ubuntu 22.04]
 - Kernel version: [e.g. Linux 5.15]
 - Device plugins version: [e.g. v0.29.0]
 - Hardware info: [e.g. SPR with QAT]
```

2024-01-09 12:58 UTC, eero-t submitted a review, later dismissed
Support requests may need device plugins version too, but otherwise texts look fine.

2024-01-09 12:58 UTC, eero-t commented on .github/ISSUE_TEMPLATE/support.md
> + - Kernel version: [e.g. Linux 5.15]
Device plugins version may be relevant here too:
```suggestion
 - Kernel version: [e.g. Linux 5.15]
  - Device plugins version: [e.g. v0.29.0]
```

2024-01-10 06:56 UTC, tkatila commented
Amended.

fyi, checks won't run on this PR as it's only .md changes.

2024-01-10 07:03 UTC, mythi approved these changes

2024-01-10 07:04 UTC, merged