gpu_nfdhook memory amount reading from sysfs
intel/intel-device-plugins-for-kubernetes pull request #482
Opened 2020-10-22 17:04 UTC by uniemimu

This adds reading of the GPU memory amount from the sysfs. As a
fallback the environment variable GPU_MEMORY_OVERRIDE remains.

Another environment variable GPU_MEMORY_RESERVED can be used to
reserve a dedicated byte amount outside of kubernetes usage.

Signed-off-by: Ukri Niemimuukko <ukri.niemimuukko@intel.com>

2020-10-23 08:11 UTC, mythi commented on cmd/gpu_nfdhook/labeler.go
> +	files, err := ioutil.ReadDir(filePath)
would `filepath.Glob()` work better, what do you think?

2020-10-23 08:11 UTC, mythi commented on cmd/gpu_nfdhook/README.md
> +GPU memory amount is read from under sysfs gt* -folders and turned into a label.
"GPU memory amount is read from sysfs gt/gt* files"?

2020-10-23 08:14 UTC, rojkov reviewed
Looks good! Just couple of nits.

2020-10-23 08:14 UTC, rojkov commented on cmd/gpu_nfdhook/labeler.go
> +// getMemoryValues reads the GPU memory amount from the system.
`getMemoryAmount`?

2020-10-23 08:14 UTC, rojkov commented on cmd/gpu_nfdhook/labeler.go
> +		klog.V(4).Info(err, "Can't read sysfs folder")
Perhaps swap the arguments for consistency?

2020-10-23 15:27 UTC, mythi approved these changes
+1

2020-10-25 06:40 UTC, mythi requested changes
taking my approval back. I noticed `gtRE` is no longer needed

2020-10-25 06:40 UTC, mythi commented on cmd/gpu_nfdhook/labeler.go
> +		gtReg:            regexp.MustCompile(gtRE),
not needed

2020-10-26 07:53 UTC, rojkov approved these changes

2020-10-26 08:14 UTC, mythi approved these changes

2020-10-26 09:38 UTC, merged