Change imagePullPolicy to Always
intel/intel-device-plugins-for-kubernetes pull request #504
Opened 2020-11-11 14:12 UTC by ozhuraki

These patches change imagePullPolicy to Always in base deployments
and demos as discussed in #400.

In case a specific imagePullPolicy is required, it can be provided
through the relevant kustomization.yaml.

Closes #400.

2020-11-11 16:50 UTC, mythi requested changes
@ozhuraki the operator code needs changes too: `pkg/controllers/*/controller.go`

I'd also want the policy documented somewhere because it has implications to users especially in today's environment with Docker's image pull request limit.

Perhaps add a sub-section to top-level README under Plugins: 

```
Pre-built plugin images
Pre-built images of the plugins are available on the Docker hub. These images are automatically built and uploaded to the hub from the latest master branch of this repository.

Release tagged images of the components are also available on the Docker hub, tagged with their release version numbers in the format x.y.z, corresponding to the branches and releases in this repository.

**Note:** the default deployment files and are operator are configured with [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) Always`
```

2020-11-12 09:35 UTC, ozhuraki commented
@mythi 

Thanks a lot for the help, done.

2020-11-12 09:47 UTC, mythi submitted a review, later dismissed
LGTM

2020-11-12 10:01 UTC, bart0sh commented
It would be nice to have instructions for resetting policy to IfNotPresent for development purposes.
I'm using my locally built images quite often to debug FPGA plugin. This change would make it harder to do as far as I understood.

2020-11-12 10:41 UTC, mythi commented
> It would be nice to have instructions for resetting policy to IfNotPresent for development purposes.

From what I'm reading, kustomize is hard for this. We could have a developer script similar to `scripts/set-version.sh` and a `make` target OR we turn this the other way around and make it `IfNotPresent` by default and document how to use, e.g., `AlwaysPullImages`  admission controller

2020-11-12 11:49 UTC, ozhuraki commented
@mythi @bart0sh 
> [...] we turn this the other way around and make it IfNotPresent by default and document how to use, e.g., AlwaysPullImages admission controller

It looks that this might be more suitable.

2020-11-12 12:03 UTC, rojkov commented
> From what I'm reading, kustomize is hard for this.

I thought kustomize is designed exactly for this kind of task. What's wrong with it? And the controllers can be parameterized to use different policy when instantiating DaemonSets.

2020-11-12 12:28 UTC, mythi commented
> I thought kustomize is designed exactly for this kind of task. What's wrong with it?

It's hard if all the images need the overlay maintained. If we are fine just documenting how to add the overlay (and leave all the debugging to the end user), it's probably easier.

2020-11-12 12:32 UTC, bart0sh commented
+1 for leaving IfNotPresent default.

Implicit upgrades caused by "Always" can be surprising for users in a negative sense I guess.

2020-11-12 12:46 UTC, rojkov commented
IMHO for release images it's safer to use `Always` from security POV. They are not supposed to have drastic changes in API by definition.

For the master branch I'd prefer `IfNotPresent` as a developer. Looks like I've just made the situation a bit more complicated :)
Perhaps extending `set-version.sh` to update the policy for a release would suffice.

2020-11-12 13:24 UTC, mythi commented
> Perhaps extending `set-version.sh` to update the policy for a release would suffice.

For the controllers too?

2020-11-12 13:30 UTC, bart0sh commented
> IMHO for release images it's safer to use Always from security POV. 

I have mixed feelings about it. From one side you're right, it's more secure. However, I'd prefer to avoid implicit things and let cluster admins decide when then want to upgrade their software.

2020-11-12 13:34 UTC, bart0sh commented
At least we seem to agree to use ```IfNotPresent``` policy for master branch. This is good for development and testing.

2020-11-12 13:37 UTC, pohly commented
> IMHO for release images it's safer to use Always from security POV. They are not supposed to have drastic changes in API by definition.

With "release images", do you mean tagged images? Those should be immutable, so `Always` just adds unnecessary overhead and requests to Docker Hub...

My two cents: use `imagePullPolicy: IfNoPresent` and then make it easy for developers to get something deployed with `imagePullPolicy: Always`. That's what we do in PMEM-CSI when deploying: https://github.com/intel/pmem-csi/blob/5c1f2b8ef2f6a8367b562a46315b290644ee2abe/test/setup-deployment.sh#L118

It's using sed here for historic reasons, but kustomize would also work.

2020-11-12 13:49 UTC, bart0sh commented
@pohly when do you use image policy Always in PMEM-CSI?

2020-11-12 14:11 UTC, rojkov commented
Alright, if release images are immutable that simplifies everything.

2020-11-12 14:11 UTC, ozhuraki commented
@mythi @bart0sh @rojkov @pohly 

OK, left our present imagePullPolicy intact, added a script for changing it and updated the doc.

Please take a look.

2020-11-12 14:59 UTC, pohly commented
> when do you use image policy Always in PMEM-CSI?

It's used when developers deploy PMEM-CSI via the test script. Normal users deploy either via YAML or operator and both use the default "IfNotPresent".

2020-11-12 15:50 UTC, mythi commented
I'm OK with the script approach and the default setting.

Just one comment: `IfNotPresent` was causing problems for some users who had an old `:devel` locally and it did not match with they were deploying from yamls. Also debugging #461 was problematic due to this too.

To get new users avoid any of these problems, perhaps we should more clearly point them to use the release tagged images.

2020-11-12 15:55 UTC, mythi commented
@ozhuraki some .yamls are missing the `imagePullPolicy` setting:

`deployments/operator/manager/manager.yaml`
`deployments/gpu_plugin/base/intel-gpu-plugin.yaml` (initContainer, check from gpu controller too)

2020-11-12 16:04 UTC, pohly commented
> Just one comment: IfNotPresent was causing problems for some users who had an old :devel locally and it did not match with they were deploying from yamls. Also debugging #461 was problematic due to this too.

I understand the motivation, but I think that changing the image policy to address this particular problem is just whacking one mole. Normal users should never use "devel" artifacts, whether it's images or YAML files.

2020-11-12 16:27 UTC, ozhuraki commented
@mythi 

> some .yamls are missing the imagePullPolicy

OK, thanks, added.

> [...] check from gpu controller too

Looks that in the controllers' code the ImagePullPolicy is present everywhere (except in patchermanager_test, which is probably the intent there):

```
pkg/fpgacontroller/patcher/patchermanager_test.go
74:					Image: "test-image",
94:					Image: "test-image",

pkg/controllers/gpu/controller.go
119:							Image:           devicePlugin.Spec.Image,
120:							ImagePullPolicy: "IfNotPresent",
184:			Image:           imageName,
185:			ImagePullPolicy: "IfNotPresent",

pkg/controllers/fpga/controller.go
106:							Image:           devicePlugin.Spec.Image,
107:							ImagePullPolicy: "IfNotPresent",
133:							Image:           devicePlugin.Spec.InitImage,
134:							ImagePullPolicy: "IfNotPresent",

pkg/controllers/qat/controller.go
96:							Image:           devicePlugin.Spec.Image,
97:							ImagePullPolicy: "IfNotPresent",

pkg/controllers/sgx/controller.go
108:							Image:           devicePlugin.Spec.InitImage,
109:							ImagePullPolicy: "IfNotPresent",
126:							Image:           devicePlugin.Spec.Image,
127:							ImagePullPolicy: "IfNotPresent",

```

2020-11-13 06:30 UTC, mythi approved these changes

2020-11-13 08:26 UTC, rojkov approved these changes

2020-11-13 08:26 UTC, merged

2020-11-16 09:52 UTC, eero-t commented
Kubernetes default for tags is "IfNotPresent", "Always" is used by default for "latest" and when there's no tag: https://kubernetes.io/docs/concepts/containers/images/#updating-images

Only moving tags (like "devel") need explicit "Always" policy, but why device plugins would use such things instead of "latest" which already implies has that?

Immutable (version) tags are fine with the default policy, it doesn't need to be explicitly set.

2020-11-16 10:12 UTC, mythi commented
> but why device plugins would use such things instead of "latest" which already implies has that?

we don't have `:latest` tag on purpose: to give clear indication that there are only released versions and a development version