update tool versions
intel/intel-device-plugins-for-kubernetes pull request #678
Opened 2021-08-20 10:25 UTC by hj-johannes-lee

Signed-off-by: Hyeongju Johannes Lee <hyeongju.lee@intel.com>

Update tool versions

2021-08-20 11:09 UTC, rojkov commented
Thanks!

Could you also update `.github/workflows/ci.yaml` accordingly? This change will trigger new linter warnings. They need to be fixed too.

2021-08-24 07:57 UTC, mythi requested changes
@rojkov while the checks are green, there are deprecation warnings coming out of `make lint`. We'll fix those too before merging (marking as 'request changes' to block merging)

2021-08-25 07:16 UTC, mythi commented on cmd/gpu_plugin/rm/gpu_plugin_resource_manager.go
> +type DeviceInfo struct {
@uniemimu PTAL. the linter error was that `NewDeviceInfo` returns unexported type. (revive/unexported-return)

2021-08-25 11:50 UTC, mythi approved these changes
Looks good to me, thanks

2021-08-25 12:00 UTC, rojkov approved these changes
Thanks! This looks perfect!

2021-08-25 12:00 UTC, merged