Intel Movidius™ S VPU support
intel/intel-device-plugins-for-kubernetes pull request #750
Opened 2021-11-15 16:55 UTC by pohkengintel

Update README and changes for new VPU.
include commit
6bdf693 Support for PCI VPU device 8086/4fc0 and 8086/4fc1

2021-11-15 17:51 UTC, bart0sh submitted a review, later dismissed
/lgtm

2021-11-15 18:51 UTC, mythi approved these changes

2021-11-15 18:55 UTC, mythi requested changes
Taking back the approval as I noticed the original commit (6bdf693) got lost. Can we fix it?

2021-11-16 03:24 UTC, pohkengintel commented
I did a cherry-pick and squash again with the 2 changes but only difference is on the date that is on 25th May (6bdf693).
The original change from (6bdf693) need to be changed. The order of data types are different from 2 forks. 

![image](https://user-images.githubusercontent.com/81682814/141889988-f6c0dbb7-c337-429d-a3bb-d67b93a30d06.png)

2021-11-16 06:04 UTC, closed without merging