operator: dsa: Handle initcontainer and ConfigMap updates
intel/intel-device-plugins-for-kubernetes pull request #761
Opened 2021-11-22 18:57 UTC by ozhuraki

Closes #729

2021-11-23 07:12 UTC, mythi requested changes
@ozhuraki LGTM, thanks! Please check the linter errors and let's rebase after the `go:embed` PR.

2021-12-01 11:48 UTC, ozhuraki commented
@bartosh @mythi 
Thanks! Rebased, sorry for a  delay.

2021-12-01 12:18 UTC, mythi commented on pkg/controllers/dsa/controller.go
> +		if container.Name == "intel-idxd-initcontainer" {
`intel-idxd-config-initcontainer`?

2021-12-01 12:26 UTC, ozhuraki commented
@mythi 
> intel-idxd-config-initcontainer?

Fixed, thanks!

2021-12-01 12:45 UTC, mythi submitted a review, later dismissed

2021-12-01 12:48 UTC, mythi commented
I missed the linter check so "conditional approval". :-)

2021-12-01 13:08 UTC, ozhuraki commented
@mythi 
Thanks! Changes:
- Fixed linter checks

2021-12-01 15:01 UTC, mythi approved these changes

2021-12-01 16:49 UTC, merged