Add a total tile count to node's labels
intel/intel-device-plugins-for-kubernetes pull request #860
Opened 2022-01-25 12:18 UTC by tkatila

This label isn't dependent on the debugfs as the platform
specific tile count is.

Signed-off-by: Tuomas Katila <tuomas.katila@intel.com>

2022-01-25 12:22 UTC, uniemimu approved these changes
lgtm

2022-01-25 12:52 UTC, bart0sh requested changes
please fix lint errors

2022-01-25 14:10 UTC, uniemimu submitted a review, later dismissed

2022-01-26 07:58 UTC, tkatila commented
Squashed

2022-01-26 08:22 UTC, uniemimu approved these changes

2022-01-26 09:39 UTC, mythi approved these changes

2022-01-26 11:08 UTC, bart0sh approved these changes
/lgtm

2022-01-26 11:09 UTC, merged