Images: Update license path for all plugin images
intel/intel-device-plugins-for-kubernetes pull request #876
Opened 2022-02-09 06:34 UTC by chaitanya1731

Updated license path to /install_root/licenses/ for all the plugin images except - intel-qat-plugin-kerneldrv, intel-vpu-plugin and intel-idxd-config-initcontainer images.

2022-02-09 09:49 UTC, bart0sh commented
@chaitanya1731 please fix e2e-fpga build failure. It's most probably caused by your changes.

2022-02-09 10:35 UTC, mythi commented
> @chaitanya1731 please fix e2e-fpga build failure. It's most probably caused by your changes.

@bart0sh the images fail to build. that makes me think can we set dependencies to actions? That is, run e2e only after everything in `ci.yaml` is passing

2022-02-09 11:09 UTC, bart0sh commented
@mythi that makes sense. Thanks for the suggestion!

2022-02-10 06:32 UTC, mythi requested changes
Thanks, this looks good but the merge commits need to be cleaned. Also, can you update:

https://github.com/intel/intel-device-plugins-for-kubernetes/blob/2e0c45b5632fc63e16226014a293b590ba905751/README.md?plain=1#L285-L287

2022-02-15 05:41 UTC, chaitanya1731 commented
Changes made as per request

2022-02-15 05:45 UTC, mythi reviewed
@chaitanya1731 looks good! one minor comment about the `README` updates

2022-02-15 05:45 UTC, mythi commented on README.md
>  `/usr/local/share/package-sources`.
with `go-licences` the source code is under the same path so this sentence should just say "Those images contain license texts and source code under `/licenses`"

2022-02-15 10:18 UTC, bart0sh approved these changes
/lgtm

2022-02-15 18:58 UTC, mythi approved these changes
Thanks!

2022-02-16 08:32 UTC, merged