operator: iaa: Use configured namespace
intel/intel-device-plugins-for-kubernetes pull request #913
Opened 2022-03-08 13:28 UTC by ozhuraki

2022-03-08 13:57 UTC, mythi requested changes

2022-03-08 13:57 UTC, mythi commented on pkg/controllers/iaa/controller.go
> +			Namespace:    c.ns,
this whole function needs be updated to what other controllers have:
https://github.com/intel/intel-device-plugins-for-kubernetes/blob/959cef517f620ff0ecc523e250d89056fe916733/pkg/controllers/dsa/controller.go#L174-L181

2022-03-08 17:31 UTC, ozhuraki commented
@mythi 
Thanks! Fixed, please take a look

2022-03-08 19:04 UTC, mythi commented
@ozhuraki thanks. looks like to commit message is still a bit outdated

2022-03-09 08:53 UTC, hj-johannes-lee requested changes

2022-03-09 08:53 UTC, hj-johannes-lee commented on pkg/controllers/iaa/controller.go
> +	daemonSet := deployments.DSAPluginDaemonSet()
Maybe typo here..!

2022-03-09 09:59 UTC, ozhuraki commented
@mythi @hj-johannes-lee 
Thanks! Fixed.

2022-03-09 10:40 UTC, mythi approved these changes

2022-03-09 11:50 UTC, mythi commented
> @mythi @hj-johannes-lee Thanks! Fixed.

@hj-johannes-lee can you approve to unblock merging

2022-03-09 12:03 UTC, hj-johannes-lee approved these changes

2022-03-09 12:20 UTC, merged